import { CheckCheck, Wand2, Mail, Globe2, PenTool, PenLine, TextSelect, Megaphone } from "lucide-react";

const metaPrompt =
  "You are AVA, an enterprise-grade LLM for business. All responses should be professional, courteous, and businesslike but friendly. You will be provided with text generated by an LLM that must be changed in the following way. You will use the provided text for reference.\n\n";

const aiOptions = [
  {
    name: "Improve Writing",
    icon: Wand2,
    prompt: `${metaPrompt} Please review the text and provide suggestions to enhance its clarity, coherence, and overall readability. Focus on improving sentence structure, grammar, punctuation, and ensure that the ideas are conveyed logically and effectively. Additionally, please check for any repetitive phrases or words and suggest alternatives for variety. Your goal is to make the text more engaging and easy to understand. You may separate your output into paragraphs where sensible.:\n\n`,
    isLoading: false,
  },
  {
    name: "Continue Writing",
    icon: PenTool,
    prompt: `${metaPrompt} Please continue writing this text. Your goal is to write a paragraph that is consistent with the style and tone of the provided text. Provide at least 3-5 sentences if possible without repeating yourself.:\n\n`,
    isLoadomg: false,
  },
  {
    name: "Fix spelling & grammar",
    icon: PenLine,
    prompt: `${metaPrompt} Please review the text and correct any spelling and grammar errors. Ensure that all sentences are properly punctuated and that the text follows standard grammar and spelling conventions. Make sure that the language is clear and free from any typographical mistakes:\n\n`,
    isLoading: false,
  },
  {
    name: "Create Email from Text",
    icon: Mail,
    prompt: `${metaPrompt} Format this text as though it were an email. Preserve lists and headings if you find them in the selected text.:\n\n`,
    isLoading: false,
  },
  {
    name: "Create Press Release",
    icon: Megaphone,
    prompt: `${metaPrompt} Format this text as though it were a press release. Format for external business communications beginning with a paragraph with a dateline, summary and other information typical of public relations communications Focus on highlighting important details, but do not make up or add details where they are not given.:\n\n`,
    isLoading: false,
  },
  {
    name: "Summarize Text",
    icon: TextSelect,
    prompt: `${metaPrompt} Summarize this text in a short paragraph of a few sentences. Take care to include all the most important points of the text. :\n\n`,
    isLoading: false,
  },
  {
    name: "Translate to Spanish",
    icon: Globe2,
    prompt: `${metaPrompt} Translate this text to Spanish:\n\n`,
    isLoading: false,
  },
  {
    name: "Translate to French",
    icon: Globe2,
    prompt: `${metaPrompt} Translate this text to German:\n\n`,
    isLoading: false,
  },
  {
    name: "Translate to Chinese",
    icon: Globe2,
    prompt: `${metaPrompt} Translate this text to Chinese:\n\n`,
    isLoading: false,
  },
];

export default aiOptions;
