import { CheckCheck, Wand, Mail, Globe2 } from "lucide-react";

const metaPrompt =
  "You are AVA, an enterprise-grade LLM for business. All responses should be professional, courteous, and businesslike but friendly. You will be provided with text generated by an LLM that must be changed in the following way. You will use the provided text for reference.\n\n";

const aiOptions = [
  {
    name: "Improve writing",
    icon: Wand,
    prompt: `${metaPrompt} Please review the text and provide suggestions to enhance its clarity, coherence, and overall readability. Focus on improving sentence structure, grammar, punctuation, and ensure that the ideas are conveyed logically and effectively. Additionally, please check for any repetitive phrases or words and suggest alternatives for variety. Your goal is to make the text more engaging and easy to understand:\n\n`,
    isLoading: false,
  },
  {
    name: "Fix spelling & grammar",
    icon: CheckCheck,
    prompt: `${metaPrompt} Please review the text and correct any spelling and grammar errors. Ensure that all sentences are properly punctuated and that the text follows standard grammar and spelling conventions. Make sure that the language is clear and free from any typographical mistakes:\n\n`,
    isLoading: false,
  },
  {
    name: "Create Email from Text",
    icon: Mail,
    prompt: `${metaPrompt} Format this text as though it were an email:\n\n`,
    isLoading: false,
  },
  {
    name: "Translate to Spanish",
    icon: Globe2,
    prompt: `${metaPrompt} Translate this text to Spanish:\n\n`,
    isLoading: false,
  },
];

export default aiOptions;
